apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: "This is a Ghost blog named ${{ values.name }}"
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}

  links:
    - url: https://${{ values.name }}.cmdbee.org
      title: Blog home
      icon: dashboard
    - url: https://${{ values.name }}.cmdbee.org/ghost
      title: Blog admin
      icon: dashboard

spec:
  type: website
  lifecycle: experimental
  owner: lamb-goat
  system: ghost-blogs
