ghost:
  ghostEmail: ${{ values.email }}
  # For some bizarre reason setting this causes Ghost to fail startup - can get from the `ghost` secret instead
  #ghostPassword: ghostPass12345
  # This works. Really could just enable email and make a new customer reset their password to start?
  existingSecret: initial-${{ values.name }}-secret
  ghostBlogTitle: ${{ values.title }}
  ghostHost: https://${{ values.name }}.terasology.io
  ghostEnableHttps: true
  ingress:
    enabled: true
    hostname: ${{ values.name }}.terasology.io
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    tls:
    - secretName: ${{ values.name }}-tls-secret
      hosts:
      - ${{ values.name }}.terasology.io
  service:
      type: ClusterIP
  # Quirk: Helm preview shows a warning if annotations here is empty, breaks creation of the service account
  serviceAccount:
    annotations:
      foo: "yay"
